name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Gradle
        run: |
          # Install Gradle manually
          wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
          unzip gradle-7.4-bin.zip
          echo "$GITHUB_WORKSPACE/gradle-7.4/bin" >> $GITHUB_PATH

      - name: Generate Gradle Wrapper
        run: |
          # Generate gradlew using the installed Gradle
          gradle wrapper

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
